language: go
go: 
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - 1.8
 - 1.9
 - "1.10"
 - "1.11"
 - "1.12"
 - tip

matrix:
  allow_failures:
    - go: tip

go_import_path: github.com/metajar/go-syslog

install:
  - go get -v -t ./...
