language: go
go: 
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - tip

matrix:
  allow_failures:
    - go: tip

install:
 - rm -rf $GOPATH/src/gopkg.in/mcuadros
 - mkdir -p $GOPATH/src/gopkg.in/mcuadros
 - ln -s $PWD $GOPATH/src/github.com/RenaultAI/go-syslog
 - cd $GOPATH/src/github.com/RenaultAI/go-syslog && go get -v -t ./...
 
script:
 - cd $GOPATH/src/github.com/RenaultAI/go-syslog && go test -v ./...
 
sudo: false
